server:
  port: 9097
spring:
  application:
    name: exchange-service
  redis:
    host: 127.0.0.1
    password: mafeng
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
