server:
  port: 9091
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: mafeng
    password: mafeng
    virtual-host: /picochain
  redis:
    host: 127.0.0.1
picochain:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: TeacherMa
    verifyCodeTemplate: SMS_191802640
