server:
  port: 9094
spring:
  application:
    name: faceRecognition-service
  redis:
    host: 127.0.0.1
    password: mafeng
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 30 # 30秒不发送就过期
picochain:
  facerecognition:
    appId:  # 你自己的appId
    sdkKey:  # 你自己的sdkKey
    faceEnginePath: /home/mafeng/ArcSoft_ArcFace_Java_Linux_x64_V3.0/libs/LINUX64/ # 引擎路径
    threshold: 0.80 # 人脸识别阈值
  idcardrecognition:
    appId:   # 你自己的appId
    appKey:    # 你自己的appKey
    secretKey:    # 你自己的secretKey
    path: /home/mafeng/IdeaProjects/picochain-web/src/picture/   # 路径
