server:
  port: 9092
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
picochain:
  jwt:
    secret: picochain@Login(Auth}*^31)&maFeng% # 登录校验的密钥
    pubKeyPath: /home/mafeng/rsa/rsa.pub # 公钥地址
    priKeyPath: /home/mafeng/rsa/rsa.pri # 私钥地址
    expire: 3000 # 过期时间,单位分钟
    cookieName: PC_TOKEN
    cookieMaxAge: 3600
