server:
  port: 9096
spring:
  application:
    name: blockchain-service
#  redis:
#    host: 127.0.0.1
#    password: mafeng
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
web3j:
  client-address: http://127.0.0.1:8545
  admin-client: true
  http-timeout-seconds: 600
picochain:
  zkp:
    path: /home/mafeng/ZKPDemo/zk/proof_data